language: node_js
node_js:
- '0.10'
- '0.11'
- '0.12'
- '4.0'
- '4.1'
before_script:
- npm install
script:
- npm run build
deploy:
  provider: npm
  email: npm@niteoholdings.com
  skip_cleanup: true
  api_key:
    secure: JFARilq1HurlPXBfEnIaxvUj/48yuPoYZGcIceOTOaBUsimORi12F5o/kXRCF1PXAoIvBF/wkuuR2+viJbmMgwgdrBW7CqpQbFKVcmOnXgtTaorFGjQIL9wKgr75KiEUzhBgx2TQNK6eIp+BbotrY32Ua/IhdlRdK2IgQFn2+O0=
  on:
    tags: true
    all_branches: true
    repo: VeriShip/grunt-niteo-awsec2
    node: '4.1'
