language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g grunt-cli
  - npm install
script:
  - grunt
deploy:
  provider: npm
  email: npm@niteoholdings.com
  skip_cleanup: true
  api_key:
    secure: "lvZXzoRDBKvat3JAOQddJewjx/UWw1hhVS413qaiB30YxUKs4K6b4hR0oAyVspG9AJUw574cdT/KcTe2aWVsV4NQWwPBtLXumtInNH1x6jsB8yeanG4np41uDOGbcZBXbWwnWN03iRdsf30nzd8M/Rw1FthQxIbpOKzOkqx8aVw="
  on:
    tags: true
    all_branches: true
    repo: NiteoSoftware/grunt-niteo-awsec2

